quarkus.rest-client.recipe-api.url=https://recipe-api.com/api/v1

# Persistent Docker PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=planner
quarkus.datasource.password=planner
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/meal_planner
quarkus.flyway.migrate-at-start=true
